apiVersion: core.jenkins-x.io/v4beta1
kind: Requirements
spec:
  autoUpdate:
    enabled: false
    schedule: ""
  cluster:
    chartRepository: http://bucketrepo.jx.svc.cluster.local/bucketrepo/charts
    clusterName: todo
    devEnvApprovers:
    - todo
    environmentGitOwner: todo
    gitKind: github
    gitName: github
    gitServer: https://github.com
    provider: openshift
    registry: ghcr.io
  environments:
  - key: dev
    owner: jamesregis
    repository: jenkins-x
  - key: staging
  - key: production
  ingress:
    domain: mycluster-dev02-bcaa1e383432c6676be4ff83548eead1-0000.us-south.containers.appdomain.cloud
    kind: ingress
    namespaceSubDomain: -jx.
    tls:
      email: ""
      enabled: false
      production: false
  pipelineUser:
    username: jamesregis
  repository: bucketrepo
  secretStorage: local
  vault: {}
  webhook: lighthouse
